### ISSUE TITLE
Fn button doesn't send MIDI when in Menu Lock mode (Matrix Pro)

### ISSUE THREAD

**Issue by luminlp** [203Electronics/MatrixOS#23]
This feature works fine on the FE but it's missing on the pro. I'm assuming it's an intended feature for the pro as well so I'm bringing it up here.

**Comment by 203Null** [comment]
It's not currently implemented because I want to reevaluate how useful it is.

**Comment by 203Null** [comment]
In OS V2.4.1, Performance mode will send a CC 121 upon enter the action menu. 

I know this is not what this issues if for but I'm thinking about if it make more sense to send out a CC instead of a Note  On+Off in menu locked mode.
